print("                               ")
print("\tSystem Administrator")
print("                                ")
print("  \t   **Needed**                ")
print("                                ")
print("                                ")
print("\tQualification   -  Degree in IT")
print("                                 ")
print("\tAge             -  20-35       ")
print("                                 ")
print("\tReligion        -  Moslem      ")
print("                                 ")
print("\tSalary          -  1000000shs  ")
print("                                 ")
print("                                 ")
print("\t\tManager"                    )
print("\tKanyike Allan              ")
print("223-063012-25852           ")

